// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

const (
	AccessTokenScopes accessTokenContextKey = "accessToken.Scopes"
)

// Defines values for AnswerClaimSource.
const (
	AnswerClaimSourceAiVerdict     AnswerClaimSource = "ai_verdict"
	AnswerClaimSourceBankLabel     AnswerClaimSource = "bank_label"
	AnswerClaimSourceCommunityVote AnswerClaimSource = "community_vote"
	AnswerClaimSourceUserNote      AnswerClaimSource = "user_note"
)

// Valid indicates whether the value is a known member of the AnswerClaimSource enum.
func (e AnswerClaimSource) Valid() bool {
	switch e {
	case AnswerClaimSourceAiVerdict:
		return true
	case AnswerClaimSourceBankLabel:
		return true
	case AnswerClaimSourceCommunityVote:
		return true
	case AnswerClaimSourceUserNote:
		return true
	default:
		return false
	}
}

// Defines values for BankKind.
const (
	BankKindCert   BankKind = "cert"
	BankKindCustom BankKind = "custom"
)

// Valid indicates whether the value is a known member of the BankKind enum.
func (e BankKind) Valid() bool {
	switch e {
	case BankKindCert:
		return true
	case BankKindCustom:
		return true
	default:
		return false
	}
}

// Defines values for BankDetailKind.
const (
	BankDetailKindCert   BankDetailKind = "cert"
	BankDetailKindCustom BankDetailKind = "custom"
)

// Valid indicates whether the value is a known member of the BankDetailKind enum.
func (e BankDetailKind) Valid() bool {
	switch e {
	case BankDetailKindCert:
		return true
	case BankDetailKindCustom:
		return true
	default:
		return false
	}
}

// Defines values for DrillContextMode.
const (
	DrillContextModeAll       DrillContextMode = "all"
	DrillContextModeContested DrillContextMode = "contested"
	DrillContextModeDue       DrillContextMode = "due"
	DrillContextModeTag       DrillContextMode = "tag"
	DrillContextModeUnseen    DrillContextMode = "unseen"
	DrillContextModeUnsure    DrillContextMode = "unsure"
	DrillContextModeWrong     DrillContextMode = "wrong"
)

// Valid indicates whether the value is a known member of the DrillContextMode enum.
func (e DrillContextMode) Valid() bool {
	switch e {
	case DrillContextModeAll:
		return true
	case DrillContextModeContested:
		return true
	case DrillContextModeDue:
		return true
	case DrillContextModeTag:
		return true
	case DrillContextModeUnseen:
		return true
	case DrillContextModeUnsure:
		return true
	case DrillContextModeWrong:
		return true
	default:
		return false
	}
}

// Defines values for ExplanationSource.
const (
	Ai     ExplanationSource = "ai"
	Editor ExplanationSource = "editor"
	User   ExplanationSource = "user"
)

// Valid indicates whether the value is a known member of the ExplanationSource enum.
func (e ExplanationSource) Valid() bool {
	switch e {
	case Ai:
		return true
	case Editor:
		return true
	case User:
		return true
	default:
		return false
	}
}

// Defines values for QuestionDetailKind.
const (
	QuestionDetailKindMulti  QuestionDetailKind = "multi"
	QuestionDetailKindSingle QuestionDetailKind = "single"
)

// Valid indicates whether the value is a known member of the QuestionDetailKind enum.
func (e QuestionDetailKind) Valid() bool {
	switch e {
	case QuestionDetailKindMulti:
		return true
	case QuestionDetailKindSingle:
		return true
	default:
		return false
	}
}

// Defines values for QuestionSummaryKind.
const (
	QuestionSummaryKindMulti  QuestionSummaryKind = "multi"
	QuestionSummaryKindSingle QuestionSummaryKind = "single"
)

// Valid indicates whether the value is a known member of the QuestionSummaryKind enum.
func (e QuestionSummaryKind) Valid() bool {
	switch e {
	case QuestionSummaryKindMulti:
		return true
	case QuestionSummaryKindSingle:
		return true
	default:
		return false
	}
}

// Defines values for ReferenceSource.
const (
	ReferenceSourceAiVerdict     ReferenceSource = "ai_verdict"
	ReferenceSourceBankLabel     ReferenceSource = "bank_label"
	ReferenceSourceCommunityVote ReferenceSource = "community_vote"
	ReferenceSourceUserNote      ReferenceSource = "user_note"
)

// Valid indicates whether the value is a known member of the ReferenceSource enum.
func (e ReferenceSource) Valid() bool {
	switch e {
	case ReferenceSourceAiVerdict:
		return true
	case ReferenceSourceBankLabel:
		return true
	case ReferenceSourceCommunityVote:
		return true
	case ReferenceSourceUserNote:
		return true
	default:
		return false
	}
}

// Defines values for ScheduleResultState.
const (
	Learning   ScheduleResultState = "learning"
	New        ScheduleResultState = "new"
	Relearning ScheduleResultState = "relearning"
	Review     ScheduleResultState = "review"
)

// Valid indicates whether the value is a known member of the ScheduleResultState enum.
func (e ScheduleResultState) Valid() bool {
	switch e {
	case Learning:
		return true
	case New:
		return true
	case Relearning:
		return true
	case Review:
		return true
	default:
		return false
	}
}

// Defines values for TagType.
const (
	TagTypeConcept TagType = "concept"
	TagTypeDomain  TagType = "domain"
	TagTypeTopic   TagType = "topic"
)

// Valid indicates whether the value is a known member of the TagType enum.
func (e TagType) Valid() bool {
	switch e {
	case TagTypeConcept:
		return true
	case TagTypeDomain:
		return true
	case TagTypeTopic:
		return true
	default:
		return false
	}
}

// Defines values for TagStatType.
const (
	TagStatTypeConcept TagStatType = "concept"
	TagStatTypeDomain  TagStatType = "domain"
	TagStatTypeTopic   TagStatType = "topic"
)

// Valid indicates whether the value is a known member of the TagStatType enum.
func (e TagStatType) Valid() bool {
	switch e {
	case TagStatTypeConcept:
		return true
	case TagStatTypeDomain:
		return true
	case TagStatTypeTopic:
		return true
	default:
		return false
	}
}

// Defines values for ListQuestionsParamsMode.
const (
	ListQuestionsParamsModeDue    ListQuestionsParamsMode = "due"
	ListQuestionsParamsModeUnseen ListQuestionsParamsMode = "unseen"
	ListQuestionsParamsModeUnsure ListQuestionsParamsMode = "unsure"
	ListQuestionsParamsModeWrong  ListQuestionsParamsMode = "wrong"
)

// Valid indicates whether the value is a known member of the ListQuestionsParamsMode enum.
func (e ListQuestionsParamsMode) Valid() bool {
	switch e {
	case ListQuestionsParamsModeDue:
		return true
	case ListQuestionsParamsModeUnseen:
		return true
	case ListQuestionsParamsModeUnsure:
		return true
	case ListQuestionsParamsModeWrong:
		return true
	default:
		return false
	}
}

// Defines values for ListBankTagsParamsType.
const (
	ListBankTagsParamsTypeConcept ListBankTagsParamsType = "concept"
	ListBankTagsParamsTypeDomain  ListBankTagsParamsType = "domain"
	ListBankTagsParamsTypeTopic   ListBankTagsParamsType = "topic"
)

// Valid indicates whether the value is a known member of the ListBankTagsParamsType enum.
func (e ListBankTagsParamsType) Valid() bool {
	switch e {
	case ListBankTagsParamsTypeConcept:
		return true
	case ListBankTagsParamsTypeDomain:
		return true
	case ListBankTagsParamsTypeTopic:
		return true
	default:
		return false
	}
}

// Defines values for GetMyTagStatsParamsType.
const (
	GetMyTagStatsParamsTypeConcept GetMyTagStatsParamsType = "concept"
	GetMyTagStatsParamsTypeDomain  GetMyTagStatsParamsType = "domain"
	GetMyTagStatsParamsTypeTopic   GetMyTagStatsParamsType = "topic"
)

// Valid indicates whether the value is a known member of the GetMyTagStatsParamsType enum.
func (e GetMyTagStatsParamsType) Valid() bool {
	switch e {
	case GetMyTagStatsParamsTypeConcept:
		return true
	case GetMyTagStatsParamsTypeDomain:
		return true
	case GetMyTagStatsParamsTypeTopic:
		return true
	default:
		return false
	}
}

// AnswerClaim 一条带来源的答案主张。同一道题可以有多条，**故意不做合并**。
// `bank_label` 与 `community_vote` 不一致的情况占 38%，
// 并列展示分歧并给出 AI 的裁决理由，正是本项目的核心价值。
type AnswerClaim struct {
	// Answer 排序后的字母集合，如 "AB"
	Answer string `json:"answer"`

	// Confidence 无则省略
	Confidence *int `json:"confidence,omitempty"`

	// Meta 如社区投票分布 {"A":80,"C":20}
	Meta *map[string]interface{} `json:"meta,omitempty"`

	// Rationale 为什么；AI 裁决必有
	Rationale *string           `json:"rationale,omitempty"`
	Source    AnswerClaimSource `json:"source"`
}

// AnswerClaimSource defines model for AnswerClaim.Source.
type AnswerClaimSource string

// AttemptInput defines model for AttemptInput.
type AttemptInput struct {
	// Chosen 排序后的字母集合，如 "AB"
	Chosen string `json:"chosen"`

	// Context 一次作答的出处 —— 用户是从哪个入口做的这道题
	Context    *DrillContext `json:"context,omitempty"`
	DurationMs *int          `json:"durationMs,omitempty"`
	QuestionId int64         `json:"questionId"`

	// Rating FSRS 标准四键自评 1=Again 2=Hard 3=Good 4=Easy
	Rating int `json:"rating"`
}

// AttemptResult defines model for AttemptResult.
type AttemptResult struct {
	// Correct 服务端按参考答案判定
	Correct bool `json:"correct"`

	// Reference 判对错用的参考答案。优先级 ai_verdict > community_vote > bank_label ——
	// AI 是唯一看过全部信息并给出理由的来源；题库标注是四个来源里
	// 最不该被无条件信任的那个（38% 与社区投票不一致）。
	// 仅用于给出反馈信号，界面仍并列展示全部主张。
	Reference *Reference `json:"reference,omitempty"`

	// Schedule 这次作答之后的记忆调度结果（FSRS）。
	//
	// **自评的可信度纠正**：`rating` 是用户按下的键、原样落进 attempt 表；
	// `effectiveRating` 是实际喂给调度器的值。两者不同时 `reasons` 说明为什么 ——
	// ⛔ 界面必须把理由显示出来，不得偷偷改调度。
	// 这与三方答案主张并列展示是同一条哲学：不替学习者下结论，把分歧摆出来。
	//
	// 当前的纠正规则：
	// · 答错却自评「掌握 / 轻松」→ 压到 1（作答顺序是【揭晓之后】才自评，
	//   答案就在眼前，不存在「只是没算准」的解释空间）
	// · 答对但用时短到读不完题面 → 压到 2（答对了，但这次答对提供不了「你会」的证据）
	// · 没有任何答案主张的题（题库里 6 道）→ 不纠正，判不了对错就不拿对错说事
	Schedule *ScheduleResult `json:"schedule,omitempty"`
}

// Bank defines model for Bank.
type Bank struct {
	Description *string  `json:"description,omitempty"`
	Id          int64    `json:"id"`
	Kind        BankKind `json:"kind"`
	Locale      string   `json:"locale"`

	// Meta 题库的**自描述展示元数据**。前端不得写死任何题库特有的词：
	// 标签轴叫什么（AWS 是「服务」、LPIC 是「命令与工具」）、考纲权重、及格线，
	// 全部从这里读。换一个题库只有这个对象不同，页面代码零改动。
	Meta BankMeta `json:"meta"`
	Name string   `json:"name"`
	Slug string   `json:"slug"`
}

// BankKind defines model for Bank.Kind.
type BankKind string

// BankDetail defines model for BankDetail.
type BankDetail struct {
	Description *string        `json:"description,omitempty"`
	Id          int64          `json:"id"`
	Kind        BankDetailKind `json:"kind"`
	Locale      string         `json:"locale"`

	// Meta 题库的**自描述展示元数据**。前端不得写死任何题库特有的词：
	// 标签轴叫什么（AWS 是「服务」、LPIC 是「命令与工具」）、考纲权重、及格线，
	// 全部从这里读。换一个题库只有这个对象不同，页面代码零改动。
	Meta BankMeta `json:"meta"`
	Name string   `json:"name"`
	Slug string   `json:"slug"`

	// Stats 题库的内容侧统计（与用户无关）
	Stats BankStats `json:"stats"`
}

// BankDetailKind defines model for BankDetail.Kind.
type BankDetailKind string

// BankMeta 题库的**自描述展示元数据**。前端不得写死任何题库特有的词：
// 标签轴叫什么（AWS 是「服务」、LPIC 是「命令与工具」）、考纲权重、及格线，
// 全部从这里读。换一个题库只有这个对象不同，页面代码零改动。
type BankMeta struct {
	// MaxScore 满分
	MaxScore *int `json:"maxScore,omitempty"`

	// PassScore 官方及格分（无则不显示及格线）
	PassScore *int `json:"passScore,omitempty"`

	// TagTypes 以标签 type（domain / topic / concept）为键
	TagTypes *map[string]TagTypeMeta `json:"tagTypes,omitempty"`
}

// BankStats 题库的内容侧统计（与用户无关）
type BankStats struct {
	// ContestedCount 题库标注与社区投票不一致的题数
	ContestedCount int `json:"contestedCount"`

	// EnrichedCount 已完成 AI 富化的题数
	EnrichedCount int `json:"enrichedCount"`

	// QuestionCount 题目总数
	QuestionCount int `json:"questionCount"`
}

// Choice defines model for Choice.
type Choice struct {
	Body  string `json:"body"`
	Label string `json:"label"`
}

// Credentials defines model for Credentials.
type Credentials struct {
	// DeviceInfo 设备标识，用于「我的登录设备」
	DeviceInfo *string `json:"deviceInfo,omitempty"`
	Password   string  `json:"password"`
	Username   string  `json:"username"`
}

// DrillContext 一次作答的出处 —— 用户是从哪个入口做的这道题
type DrillContext struct {
	Mode DrillContextMode `json:"mode"`

	// TagId mode=tag 时必填
	TagId *int64 `json:"tagId,omitempty"`
}

// DrillContextMode defines model for DrillContext.Mode.
type DrillContextMode string

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// Explanation defines model for Explanation.
type Explanation struct {
	Body   string            `json:"body"`
	Locale string            `json:"locale"`
	Source ExplanationSource `json:"source"`
}

// ExplanationSource defines model for Explanation.Source.
type ExplanationSource string

// FocusCursor defines model for FocusCursor.
type FocusCursor struct {
	// Context 一次作答的出处 —— 用户是从哪个入口做的这道题
	Context DrillContext `json:"context"`

	// Done 集合内做过的题数；只有 tag / contested 有意义
	Done *int `json:"done,omitempty"`

	// Label mode=tag 时为标签 value，否则为 mode 名
	Label  string    `json:"label"`
	LastAt time.Time `json:"lastAt"`

	// Tag 通用 (type, value) 结构，不硬编码任何特定题库的分类体系
	Tag *Tag `json:"tag,omitempty"`

	// Total 集合当前大小
	Total int `json:"total"`
}

// Overview defines model for Overview.
type Overview struct {
	// SeenTotal 跨题库做过的题数（去重）
	SeenTotal int `json:"seenTotal"`

	// StreakDays 连续有作答的自然日数（含今天；今天没做则从昨天起算）
	StreakDays int `json:"streakDays"`

	// TodayCount 今天的作答次数
	TodayCount int `json:"todayCount"`
}

// Progress defines model for Progress.
type Progress struct {
	// AttemptCount 总作答次数（含重做）
	AttemptCount int    `json:"attemptCount"`
	BankSlug     string `json:"bankSlug"`

	// CorrectCount 最近一次作答为对的题数
	CorrectCount int `json:"correctCount"`

	// DueCount FSRS 复习队列里已到期的题数。
	// ⚠️ **不含从没做过的题** —— 那些题没有卡片，属于「没做过」入口。
	// 两者混进一个数字，「今天要复习 300 题」就失去意义了，
	// 而那正是间隔重复最劝退的失败模式。
	DueCount     int        `json:"dueCount"`
	LastActiveAt *time.Time `json:"lastActiveAt,omitempty"`

	// QuestionCount 题库总题数
	QuestionCount int `json:"questionCount"`

	// SeenCount 做过的题数（去重）
	SeenCount int `json:"seenCount"`

	// UnsureCount 最近一次自评 ≤2 的题数
	UnsureCount int `json:"unsureCount"`

	// WrongCount 最近一次作答为错的题数
	WrongCount int `json:"wrongCount"`
}

// QuestionDetail defines model for QuestionDetail.
type QuestionDetail struct {
	BankSlug string        `json:"bankSlug"`
	Choices  []Choice      `json:"choices"`
	Claims   []AnswerClaim `json:"claims"`

	// Contested 题库标注与社区投票是否不一致
	Contested bool `json:"contested"`

	// DataIssue 题目本身有缺陷时的说明（题库脏点），正常不出现
	DataIssue *string `json:"dataIssue,omitempty"`

	// Enriched 是否已完成 AI 富化
	Enriched     bool          `json:"enriched"`
	Explanations []Explanation `json:"explanations"`

	// ExternalNo 原题号，用于溯源
	ExternalNo int                `json:"externalNo"`
	Id         int64              `json:"id"`
	Kind       QuestionDetailKind `json:"kind"`
	PickCount  int                `json:"pickCount"`

	// Reference 判对错用的参考答案。优先级 ai_verdict > community_vote > bank_label ——
	// AI 是唯一看过全部信息并给出理由的来源；题库标注是四个来源里
	// 最不该被无条件信任的那个（38% 与社区投票不一致）。
	// 仅用于给出反馈信号，界面仍并列展示全部主张。
	Reference *Reference `json:"reference,omitempty"`
	Stem      string     `json:"stem"`
	Tags      []Tag      `json:"tags"`

	// Warnings P0 解析阶段的告警，不静默丢弃
	Warnings *[]string `json:"warnings,omitempty"`
}

// QuestionDetailKind defines model for QuestionDetail.Kind.
type QuestionDetailKind string

// QuestionPage defines model for QuestionPage.
type QuestionPage struct {
	Items  []QuestionSummary `json:"items"`
	Limit  int               `json:"limit"`
	Offset int               `json:"offset"`
	Total  int               `json:"total"`
}

// QuestionSummary defines model for QuestionSummary.
type QuestionSummary struct {
	// Contested 题库标注与社区投票是否不一致
	Contested bool `json:"contested"`

	// Enriched 是否已完成 AI 富化
	Enriched bool `json:"enriched"`

	// ExternalNo 原题号，用于溯源
	ExternalNo int                 `json:"externalNo"`
	Id         int64               `json:"id"`
	Kind       QuestionSummaryKind `json:"kind"`
	PickCount  int                 `json:"pickCount"`
	Stem       string              `json:"stem"`
}

// QuestionSummaryKind defines model for QuestionSummary.Kind.
type QuestionSummaryKind string

// Reference 判对错用的参考答案。优先级 ai_verdict > community_vote > bank_label ——
// AI 是唯一看过全部信息并给出理由的来源；题库标注是四个来源里
// 最不该被无条件信任的那个（38% 与社区投票不一致）。
// 仅用于给出反馈信号，界面仍并列展示全部主张。
type Reference struct {
	Answer string          `json:"answer"`
	Source ReferenceSource `json:"source"`
}

// ReferenceSource defines model for Reference.Source.
type ReferenceSource string

// RefreshRequest defines model for RefreshRequest.
type RefreshRequest struct {
	RefreshToken string `json:"refreshToken"`
}

// Resume 「继续学习」的两条轨道，全部从 attempt 推导：
// · sequential —— 顺序进度：题号最小的没做过的题，无需存状态
// · focus —— 上次专项：最近一条 context.mode ∉ {unseen, all} 的作答的出处；从未做过专项时缺省
type Resume struct {
	BankSlug string       `json:"bankSlug"`
	Focus    *FocusCursor `json:"focus,omitempty"`

	// Sequential questionId 缺省 = 题库已全部做过一遍
	Sequential SequentialCursor `json:"sequential"`
}

// ScheduleResult 这次作答之后的记忆调度结果（FSRS）。
//
// **自评的可信度纠正**：`rating` 是用户按下的键、原样落进 attempt 表；
// `effectiveRating` 是实际喂给调度器的值。两者不同时 `reasons` 说明为什么 ——
// ⛔ 界面必须把理由显示出来，不得偷偷改调度。
// 这与三方答案主张并列展示是同一条哲学：不替学习者下结论，把分歧摆出来。
//
// 当前的纠正规则：
// · 答错却自评「掌握 / 轻松」→ 压到 1（作答顺序是【揭晓之后】才自评，
//
//	答案就在眼前，不存在「只是没算准」的解释空间）
//
// · 答对但用时短到读不完题面 → 压到 2（答对了，但这次答对提供不了「你会」的证据）
// · 没有任何答案主张的题（题库里 6 道）→ 不纠正，判不了对错就不拿对错说事
type ScheduleResult struct {
	// Due 这道题下次该出现的时间（UTC）
	Due time.Time `json:"due"`

	// EffectiveRating 实际用于调度的评分，只会 ≤ rating
	EffectiveRating int `json:"effectiveRating"`

	// Rating 用户按下的自评键
	Rating int `json:"rating"`

	// Reasons 纠正理由，未纠正时为空数组
	Reasons []string `json:"reasons"`

	// State 调度后的卡片状态
	State ScheduleResultState `json:"state"`
}

// ScheduleResultState 调度后的卡片状态
type ScheduleResultState string

// SequentialCursor questionId 缺省 = 题库已全部做过一遍
type SequentialCursor struct {
	// DoneCount 做过的题数（去重）
	DoneCount  int  `json:"doneCount"`
	ExternalNo *int `json:"externalNo,omitempty"`

	// LastAt 上次顺序作答时间
	LastAt     *time.Time `json:"lastAt,omitempty"`
	QuestionId *int64     `json:"questionId,omitempty"`
	Stem       *string    `json:"stem,omitempty"`

	// TotalCount 题库总题数
	TotalCount int `json:"totalCount"`
}

// SsoExchange defines model for SsoExchange.
type SsoExchange struct {
	// DeviceInfo 设备标识，用于「我的登录设备」
	DeviceInfo *string `json:"deviceInfo,omitempty"`

	// IdToken Akasha 签发的 id_token（由本 API 验签）
	IdToken string `json:"idToken"`
}

// StudySession defines model for StudySession.
type StudySession struct {
	BankName string `json:"bankName"`
	BankSlug string `json:"bankSlug"`

	// Context 一次作答的出处 —— 用户是从哪个入口做的这道题
	Context DrillContext `json:"context"`
	Correct int          `json:"correct"`
	Count   int          `json:"count"`
	EndedAt time.Time    `json:"endedAt"`

	// FirstNo 顺序刷时的起止题号，便于显示 "#400–#413"
	FirstNo *int `json:"firstNo,omitempty"`

	// Label mode=tag 时为标签名，否则为 mode
	Label     string    `json:"label"`
	LastNo    *int      `json:"lastNo,omitempty"`
	StartedAt time.Time `json:"startedAt"`

	// Tag 通用 (type, value) 结构，不硬编码任何特定题库的分类体系
	Tag *Tag `json:"tag,omitempty"`
}

// Tag 通用 (type, value) 结构，不硬编码任何特定题库的分类体系
type Tag struct {
	I18n *map[string]string `json:"i18n,omitempty"`
	Id   int64              `json:"id"`

	// QuestionCount 挂在该标签下的题数
	QuestionCount *int    `json:"questionCount,omitempty"`
	Type          TagType `json:"type"`
	Value         string  `json:"value"`
}

// TagType defines model for Tag.Type.
type TagType string

// TagStat defines model for TagStat.
type TagStat struct {
	Correct int                `json:"correct"`
	I18n    *map[string]string `json:"i18n,omitempty"`

	// Rate 正确率 0-100
	Rate  float32 `json:"rate"`
	TagId int64   `json:"tagId"`

	// Total 该标签下做过的题数
	Total int         `json:"total"`
	Type  TagStatType `json:"type"`
	Value string      `json:"value"`
}

// TagStatType defines model for TagStat.Type.
type TagStatType string

// TagTypeMeta defines model for TagTypeMeta.
type TagTypeMeta struct {
	// Label locale → 该标签轴的显示名
	Label *map[string]string `json:"label,omitempty"`

	// Weights 标签 value → 官方权重百分比（通常只有 domain 轴有）
	Weights *map[string]float32 `json:"weights,omitempty"`
}

// TokenPair access 是 JWT（不落库，TTL 1h）；refresh 是不透明随机串（落库，可吊销）。
// 对齐 geass-v3：refresh 不做成 JWT —— 生命周期以月计的凭证必须能撤回。
type TokenPair struct {
	AccessToken string `json:"accessToken"`

	// AccountId 账号 id（canonical UUIDv7 文本）
	AccountId string `json:"accountId"`
	Display   string `json:"display"`

	// ExpiresIn access token 剩余秒数（非绝对时间，免受客户端时钟偏差影响）
	ExpiresIn    int    `json:"expiresIn"`
	RefreshToken string `json:"refreshToken"`
}

// BankQuery defines model for BankQuery.
type BankQuery = string

// Slug defines model for Slug.
type Slug = string

// NotFound defines model for NotFound.
type NotFound = Error

// TooManyRequests defines model for TooManyRequests.
type TooManyRequests = Error

// accessTokenContextKey is the context key for accessToken security scheme
type accessTokenContextKey string

// ListQuestionsParams defines parameters for ListQuestions.
type ListQuestionsParams struct {
	// Tag 标签 id，可重复；多个标签取交集
	Tag *[]int64 `form:"tag,omitempty" json:"tag,omitempty"`

	// Contested 只返回存在答案分歧的题（题库标注 ≠ 社区投票）
	Contested *bool `form:"contested,omitempty" json:"contested,omitempty"`

	// Enriched 只返回已完成 AI 富化的题
	Enriched *bool `form:"enriched,omitempty" json:"enriched,omitempty"`

	// Mode 学习模式过滤（全部需要会话，账号取自 JWT 而非请求参数）：
	// wrong = 最近一次作答是错的；unsure = 最近一次自评 rating ≤ 2；
	// unseen = 从未作答；
	// due = FSRS 复习队列，卡片已到期。
	//
	// ⚠️ due 与 unseen 互斥且不重叠：没做过的题没有卡片，不算「到期」。
	// 两者混进一个数字会让「今天要复习 300 题」失去意义。
	// ⚠️ due 按【到期时间】升序返回，其余模式按原题号 —— 复习队列不是浏览列表。
	Mode   *ListQuestionsParamsMode `form:"mode,omitempty" json:"mode,omitempty"`
	Limit  *int                     `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int                     `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListQuestionsParamsMode defines parameters for ListQuestions.
type ListQuestionsParamsMode string

// ListBankTagsParams defines parameters for ListBankTags.
type ListBankTagsParams struct {
	// Type 只返回某一类标签
	Type *ListBankTagsParamsType `form:"type,omitempty" json:"type,omitempty"`
}

// ListBankTagsParamsType defines parameters for ListBankTags.
type ListBankTagsParamsType string

// GetMyProgressParams defines parameters for GetMyProgress.
type GetMyProgressParams struct {
	// Bank 题库 slug；缺省 = 当前题库（现阶段为第一个题库）
	Bank *BankQuery `form:"bank,omitempty" json:"bank,omitempty"`
}

// GetMyRecentParams defines parameters for GetMyRecent.
type GetMyRecentParams struct {
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetMyResumeParams defines parameters for GetMyResume.
type GetMyResumeParams struct {
	// Bank 题库 slug；缺省 = 当前题库（现阶段为第一个题库）
	Bank *BankQuery `form:"bank,omitempty" json:"bank,omitempty"`
}

// GetMyTagStatsParams defines parameters for GetMyTagStats.
type GetMyTagStatsParams struct {
	// Bank 题库 slug；缺省 = 当前题库（现阶段为第一个题库）
	Bank *BankQuery              `form:"bank,omitempty" json:"bank,omitempty"`
	Type GetMyTagStatsParamsType `form:"type" json:"type"`

	// MinAttempts 至少做过几道才纳入（样本太小的标签正确率没有意义）
	MinAttempts *int `form:"minAttempts,omitempty" json:"minAttempts,omitempty"`
}

// GetMyTagStatsParamsType defines parameters for GetMyTagStats.
type GetMyTagStatsParamsType string

// RecordAttemptJSONRequestBody defines body for RecordAttempt for application/json ContentType.
type RecordAttemptJSONRequestBody = AttemptInput

// LogoutJSONRequestBody defines body for Logout for application/json ContentType.
type LogoutJSONRequestBody = RefreshRequest

// PasswordLoginJSONRequestBody defines body for PasswordLogin for application/json ContentType.
type PasswordLoginJSONRequestBody = Credentials

// RefreshTokenJSONRequestBody defines body for RefreshToken for application/json ContentType.
type RefreshTokenJSONRequestBody = RefreshRequest

// SsoExchangeJSONRequestBody defines body for SsoExchange for application/json ContentType.
type SsoExchangeJSONRequestBody = SsoExchange

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// 记录一次作答（对错由服务端按参考答案判定）
	// (POST /attempts)
	RecordAttempt(w http.ResponseWriter, r *http.Request)
	// 登出（吊销该会话）
	// (POST /auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// 用户名密码登录
	// (POST /auth/password)
	PasswordLogin(w http.ResponseWriter, r *http.Request)
	// 用 refresh token 换新的 access token
	// (POST /auth/refresh)
	RefreshToken(w http.ResponseWriter, r *http.Request)
	// 用 Akasha id_token 换取本 API 的 token
	// (POST /auth/sso)
	SsoExchange(w http.ResponseWriter, r *http.Request)
	// 题库列表
	// (GET /banks)
	ListBanks(w http.ResponseWriter, r *http.Request)
	// 题库详情与统计
	// (GET /banks/{slug})
	GetBank(w http.ResponseWriter, r *http.Request, slug Slug)
	// 题目列表（分页 + 标签筛选）
	// (GET /banks/{slug}/questions)
	ListQuestions(w http.ResponseWriter, r *http.Request, slug Slug, params ListQuestionsParams)
	// 题库的标签列表（用于筛选与正确率热图）
	// (GET /banks/{slug}/tags)
	ListBankTags(w http.ResponseWriter, r *http.Request, slug Slug, params ListBankTagsParams)
	// 跨题库总览（今天 / 连续天数 / 累计）
	// (GET /me/overview)
	GetMyOverview(w http.ResponseWriter, r *http.Request)
	// 我的学习进度总览
	// (GET /me/progress)
	GetMyProgress(w http.ResponseWriter, r *http.Request, params GetMyProgressParams)
	// 最近的学习会话（跨题库）
	// (GET /me/recent)
	GetMyRecent(w http.ResponseWriter, r *http.Request, params GetMyRecentParams)
	// 继续学习（上次刷到哪）
	// (GET /me/resume)
	GetMyResume(w http.ResponseWriter, r *http.Request, params GetMyResumeParams)
	// 按标签的正确率（「我哪里不会」）
	// (GET /me/tag-stats)
	GetMyTagStats(w http.ResponseWriter, r *http.Request, params GetMyTagStatsParams)
	// 单题详情（题干 + 选项 + 各方答案主张 + 解析 + 标签）
	// (GET /questions/{id})
	GetQuestion(w http.ResponseWriter, r *http.Request, id int64)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// 记录一次作答（对错由服务端按参考答案判定）
// (POST /attempts)
func (_ Unimplemented) RecordAttempt(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 登出（吊销该会话）
// (POST /auth/logout)
func (_ Unimplemented) Logout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 用户名密码登录
// (POST /auth/password)
func (_ Unimplemented) PasswordLogin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 用 refresh token 换新的 access token
// (POST /auth/refresh)
func (_ Unimplemented) RefreshToken(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 用 Akasha id_token 换取本 API 的 token
// (POST /auth/sso)
func (_ Unimplemented) SsoExchange(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 题库列表
// (GET /banks)
func (_ Unimplemented) ListBanks(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 题库详情与统计
// (GET /banks/{slug})
func (_ Unimplemented) GetBank(w http.ResponseWriter, r *http.Request, slug Slug) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 题目列表（分页 + 标签筛选）
// (GET /banks/{slug}/questions)
func (_ Unimplemented) ListQuestions(w http.ResponseWriter, r *http.Request, slug Slug, params ListQuestionsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 题库的标签列表（用于筛选与正确率热图）
// (GET /banks/{slug}/tags)
func (_ Unimplemented) ListBankTags(w http.ResponseWriter, r *http.Request, slug Slug, params ListBankTagsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 跨题库总览（今天 / 连续天数 / 累计）
// (GET /me/overview)
func (_ Unimplemented) GetMyOverview(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 我的学习进度总览
// (GET /me/progress)
func (_ Unimplemented) GetMyProgress(w http.ResponseWriter, r *http.Request, params GetMyProgressParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 最近的学习会话（跨题库）
// (GET /me/recent)
func (_ Unimplemented) GetMyRecent(w http.ResponseWriter, r *http.Request, params GetMyRecentParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 继续学习（上次刷到哪）
// (GET /me/resume)
func (_ Unimplemented) GetMyResume(w http.ResponseWriter, r *http.Request, params GetMyResumeParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 按标签的正确率（「我哪里不会」）
// (GET /me/tag-stats)
func (_ Unimplemented) GetMyTagStats(w http.ResponseWriter, r *http.Request, params GetMyTagStatsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 单题详情（题干 + 选项 + 各方答案主张 + 解析 + 标签）
// (GET /questions/{id})
func (_ Unimplemented) GetQuestion(w http.ResponseWriter, r *http.Request, id int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// RecordAttempt operation middleware
func (siw *ServerInterfaceWrapper) RecordAttempt(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, AccessTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RecordAttempt(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PasswordLogin operation middleware
func (siw *ServerInterfaceWrapper) PasswordLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PasswordLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RefreshToken operation middleware
func (siw *ServerInterfaceWrapper) RefreshToken(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RefreshToken(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SsoExchange operation middleware
func (siw *ServerInterfaceWrapper) SsoExchange(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SsoExchange(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListBanks operation middleware
func (siw *ServerInterfaceWrapper) ListBanks(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, AccessTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListBanks(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetBank operation middleware
func (siw *ServerInterfaceWrapper) GetBank(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "slug" -------------
	var slug Slug

	err = runtime.BindStyledParameterWithOptions("simple", "slug", chi.URLParam(r, "slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slug", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, AccessTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetBank(w, r, slug)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListQuestions operation middleware
func (siw *ServerInterfaceWrapper) ListQuestions(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "slug" -------------
	var slug Slug

	err = runtime.BindStyledParameterWithOptions("simple", "slug", chi.URLParam(r, "slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slug", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, AccessTokenScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListQuestionsParams

	// ------------- Optional query parameter "tag" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "tag", r.URL.Query(), &params.Tag, runtime.BindQueryParameterOptions{Type: "array", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "tag"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tag", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "contested" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "contested", r.URL.Query(), &params.Contested, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "contested"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "contested", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "enriched" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "enriched", r.URL.Query(), &params.Enriched, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "enriched"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "enriched", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "mode" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "mode", r.URL.Query(), &params.Mode, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "mode"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "mode", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "offset"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListQuestions(w, r, slug, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListBankTags operation middleware
func (siw *ServerInterfaceWrapper) ListBankTags(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "slug" -------------
	var slug Slug

	err = runtime.BindStyledParameterWithOptions("simple", "slug", chi.URLParam(r, "slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slug", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, AccessTokenScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListBankTagsParams

	// ------------- Optional query parameter "type" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "type", r.URL.Query(), &params.Type, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "type"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "type", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListBankTags(w, r, slug, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMyOverview operation middleware
func (siw *ServerInterfaceWrapper) GetMyOverview(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, AccessTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMyOverview(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMyProgress operation middleware
func (siw *ServerInterfaceWrapper) GetMyProgress(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, AccessTokenScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetMyProgressParams

	// ------------- Optional query parameter "bank" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "bank", r.URL.Query(), &params.Bank, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "bank"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "bank", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMyProgress(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMyRecent operation middleware
func (siw *ServerInterfaceWrapper) GetMyRecent(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, AccessTokenScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetMyRecentParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMyRecent(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMyResume operation middleware
func (siw *ServerInterfaceWrapper) GetMyResume(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, AccessTokenScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetMyResumeParams

	// ------------- Optional query parameter "bank" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "bank", r.URL.Query(), &params.Bank, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "bank"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "bank", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMyResume(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMyTagStats operation middleware
func (siw *ServerInterfaceWrapper) GetMyTagStats(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, AccessTokenScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetMyTagStatsParams

	// ------------- Optional query parameter "bank" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "bank", r.URL.Query(), &params.Bank, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "bank"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "bank", Err: err})
		}
		return
	}

	// ------------- Required query parameter "type" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "type", r.URL.Query(), &params.Type, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "type"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "type", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "minAttempts" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "minAttempts", r.URL.Query(), &params.MinAttempts, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "minAttempts"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "minAttempts", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMyTagStats(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetQuestion operation middleware
func (siw *ServerInterfaceWrapper) GetQuestion(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, AccessTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetQuestion(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/attempts", wrapper.RecordAttempt)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/logout", wrapper.Logout)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/password", wrapper.PasswordLogin)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/refresh", wrapper.RefreshToken)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/sso", wrapper.SsoExchange)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/banks", wrapper.ListBanks)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/banks/{slug}", wrapper.GetBank)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/banks/{slug}/questions", wrapper.ListQuestions)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/banks/{slug}/tags", wrapper.ListBankTags)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/me/overview", wrapper.GetMyOverview)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/me/progress", wrapper.GetMyProgress)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/me/recent", wrapper.GetMyRecent)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/me/resume", wrapper.GetMyResume)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/me/tag-stats", wrapper.GetMyTagStats)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/questions/{id}", wrapper.GetQuestion)
	})

	return r
}

type NotFoundJSONResponse Error

type TooManyRequestsJSONResponse Error

type RecordAttemptRequestObject struct {
	Body *RecordAttemptJSONRequestBody
}

type RecordAttemptResponseObject interface {
	VisitRecordAttemptResponse(w http.ResponseWriter) error
}

type RecordAttempt200JSONResponse AttemptResult

func (response RecordAttempt200JSONResponse) VisitRecordAttemptResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type RecordAttempt404JSONResponse struct{ NotFoundJSONResponse }

func (response RecordAttempt404JSONResponse) VisitRecordAttemptResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type LogoutRequestObject struct {
	Body *LogoutJSONRequestBody
}

type LogoutResponseObject interface {
	VisitLogoutResponse(w http.ResponseWriter) error
}

type Logout204Response struct {
}

func (response Logout204Response) VisitLogoutResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type PasswordLoginRequestObject struct {
	Body *PasswordLoginJSONRequestBody
}

type PasswordLoginResponseObject interface {
	VisitPasswordLoginResponse(w http.ResponseWriter) error
}

type PasswordLogin200JSONResponse TokenPair

func (response PasswordLogin200JSONResponse) VisitPasswordLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PasswordLogin401JSONResponse Error

func (response PasswordLogin401JSONResponse) VisitPasswordLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PasswordLogin429JSONResponse struct{ TooManyRequestsJSONResponse }

func (response PasswordLogin429JSONResponse) VisitPasswordLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshTokenRequestObject struct {
	Body *RefreshTokenJSONRequestBody
}

type RefreshTokenResponseObject interface {
	VisitRefreshTokenResponse(w http.ResponseWriter) error
}

type RefreshToken200JSONResponse TokenPair

func (response RefreshToken200JSONResponse) VisitRefreshTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshToken401JSONResponse Error

func (response RefreshToken401JSONResponse) VisitRefreshTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type SsoExchangeRequestObject struct {
	Body *SsoExchangeJSONRequestBody
}

type SsoExchangeResponseObject interface {
	VisitSsoExchangeResponse(w http.ResponseWriter) error
}

type SsoExchange200JSONResponse TokenPair

func (response SsoExchange200JSONResponse) VisitSsoExchangeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SsoExchange401JSONResponse Error

func (response SsoExchange401JSONResponse) VisitSsoExchangeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type SsoExchange429JSONResponse struct{ TooManyRequestsJSONResponse }

func (response SsoExchange429JSONResponse) VisitSsoExchangeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type ListBanksRequestObject struct {
}

type ListBanksResponseObject interface {
	VisitListBanksResponse(w http.ResponseWriter) error
}

type ListBanks200JSONResponse []Bank

func (response ListBanks200JSONResponse) VisitListBanksResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetBankRequestObject struct {
	Slug Slug `json:"slug"`
}

type GetBankResponseObject interface {
	VisitGetBankResponse(w http.ResponseWriter) error
}

type GetBank200JSONResponse BankDetail

func (response GetBank200JSONResponse) VisitGetBankResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetBank404JSONResponse struct{ NotFoundJSONResponse }

func (response GetBank404JSONResponse) VisitGetBankResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListQuestionsRequestObject struct {
	Slug   Slug `json:"slug"`
	Params ListQuestionsParams
}

type ListQuestionsResponseObject interface {
	VisitListQuestionsResponse(w http.ResponseWriter) error
}

type ListQuestions200JSONResponse QuestionPage

func (response ListQuestions200JSONResponse) VisitListQuestionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListQuestions404JSONResponse struct{ NotFoundJSONResponse }

func (response ListQuestions404JSONResponse) VisitListQuestionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListBankTagsRequestObject struct {
	Slug   Slug `json:"slug"`
	Params ListBankTagsParams
}

type ListBankTagsResponseObject interface {
	VisitListBankTagsResponse(w http.ResponseWriter) error
}

type ListBankTags200JSONResponse []Tag

func (response ListBankTags200JSONResponse) VisitListBankTagsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListBankTags404JSONResponse struct{ NotFoundJSONResponse }

func (response ListBankTags404JSONResponse) VisitListBankTagsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetMyOverviewRequestObject struct {
}

type GetMyOverviewResponseObject interface {
	VisitGetMyOverviewResponse(w http.ResponseWriter) error
}

type GetMyOverview200JSONResponse Overview

func (response GetMyOverview200JSONResponse) VisitGetMyOverviewResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMyProgressRequestObject struct {
	Params GetMyProgressParams
}

type GetMyProgressResponseObject interface {
	VisitGetMyProgressResponse(w http.ResponseWriter) error
}

type GetMyProgress200JSONResponse Progress

func (response GetMyProgress200JSONResponse) VisitGetMyProgressResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMyRecentRequestObject struct {
	Params GetMyRecentParams
}

type GetMyRecentResponseObject interface {
	VisitGetMyRecentResponse(w http.ResponseWriter) error
}

type GetMyRecent200JSONResponse []StudySession

func (response GetMyRecent200JSONResponse) VisitGetMyRecentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMyResumeRequestObject struct {
	Params GetMyResumeParams
}

type GetMyResumeResponseObject interface {
	VisitGetMyResumeResponse(w http.ResponseWriter) error
}

type GetMyResume200JSONResponse Resume

func (response GetMyResume200JSONResponse) VisitGetMyResumeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMyTagStatsRequestObject struct {
	Params GetMyTagStatsParams
}

type GetMyTagStatsResponseObject interface {
	VisitGetMyTagStatsResponse(w http.ResponseWriter) error
}

type GetMyTagStats200JSONResponse []TagStat

func (response GetMyTagStats200JSONResponse) VisitGetMyTagStatsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetQuestionRequestObject struct {
	Id int64 `json:"id"`
}

type GetQuestionResponseObject interface {
	VisitGetQuestionResponse(w http.ResponseWriter) error
}

type GetQuestion200JSONResponse QuestionDetail

func (response GetQuestion200JSONResponse) VisitGetQuestionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetQuestion404JSONResponse struct{ NotFoundJSONResponse }

func (response GetQuestion404JSONResponse) VisitGetQuestionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// 记录一次作答（对错由服务端按参考答案判定）
	// (POST /attempts)
	RecordAttempt(ctx context.Context, request RecordAttemptRequestObject) (RecordAttemptResponseObject, error)
	// 登出（吊销该会话）
	// (POST /auth/logout)
	Logout(ctx context.Context, request LogoutRequestObject) (LogoutResponseObject, error)
	// 用户名密码登录
	// (POST /auth/password)
	PasswordLogin(ctx context.Context, request PasswordLoginRequestObject) (PasswordLoginResponseObject, error)
	// 用 refresh token 换新的 access token
	// (POST /auth/refresh)
	RefreshToken(ctx context.Context, request RefreshTokenRequestObject) (RefreshTokenResponseObject, error)
	// 用 Akasha id_token 换取本 API 的 token
	// (POST /auth/sso)
	SsoExchange(ctx context.Context, request SsoExchangeRequestObject) (SsoExchangeResponseObject, error)
	// 题库列表
	// (GET /banks)
	ListBanks(ctx context.Context, request ListBanksRequestObject) (ListBanksResponseObject, error)
	// 题库详情与统计
	// (GET /banks/{slug})
	GetBank(ctx context.Context, request GetBankRequestObject) (GetBankResponseObject, error)
	// 题目列表（分页 + 标签筛选）
	// (GET /banks/{slug}/questions)
	ListQuestions(ctx context.Context, request ListQuestionsRequestObject) (ListQuestionsResponseObject, error)
	// 题库的标签列表（用于筛选与正确率热图）
	// (GET /banks/{slug}/tags)
	ListBankTags(ctx context.Context, request ListBankTagsRequestObject) (ListBankTagsResponseObject, error)
	// 跨题库总览（今天 / 连续天数 / 累计）
	// (GET /me/overview)
	GetMyOverview(ctx context.Context, request GetMyOverviewRequestObject) (GetMyOverviewResponseObject, error)
	// 我的学习进度总览
	// (GET /me/progress)
	GetMyProgress(ctx context.Context, request GetMyProgressRequestObject) (GetMyProgressResponseObject, error)
	// 最近的学习会话（跨题库）
	// (GET /me/recent)
	GetMyRecent(ctx context.Context, request GetMyRecentRequestObject) (GetMyRecentResponseObject, error)
	// 继续学习（上次刷到哪）
	// (GET /me/resume)
	GetMyResume(ctx context.Context, request GetMyResumeRequestObject) (GetMyResumeResponseObject, error)
	// 按标签的正确率（「我哪里不会」）
	// (GET /me/tag-stats)
	GetMyTagStats(ctx context.Context, request GetMyTagStatsRequestObject) (GetMyTagStatsResponseObject, error)
	// 单题详情（题干 + 选项 + 各方答案主张 + 解析 + 标签）
	// (GET /questions/{id})
	GetQuestion(ctx context.Context, request GetQuestionRequestObject) (GetQuestionResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// RecordAttempt operation middleware
func (sh *strictHandler) RecordAttempt(w http.ResponseWriter, r *http.Request) {
	var request RecordAttemptRequestObject

	var body RecordAttemptJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RecordAttempt(ctx, request.(RecordAttemptRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RecordAttempt")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RecordAttemptResponseObject); ok {
		if err := validResponse.VisitRecordAttemptResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Logout operation middleware
func (sh *strictHandler) Logout(w http.ResponseWriter, r *http.Request) {
	var request LogoutRequestObject

	var body LogoutJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Logout(ctx, request.(LogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Logout")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LogoutResponseObject); ok {
		if err := validResponse.VisitLogoutResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PasswordLogin operation middleware
func (sh *strictHandler) PasswordLogin(w http.ResponseWriter, r *http.Request) {
	var request PasswordLoginRequestObject

	var body PasswordLoginJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PasswordLogin(ctx, request.(PasswordLoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PasswordLogin")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PasswordLoginResponseObject); ok {
		if err := validResponse.VisitPasswordLoginResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RefreshToken operation middleware
func (sh *strictHandler) RefreshToken(w http.ResponseWriter, r *http.Request) {
	var request RefreshTokenRequestObject

	var body RefreshTokenJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RefreshToken(ctx, request.(RefreshTokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RefreshToken")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RefreshTokenResponseObject); ok {
		if err := validResponse.VisitRefreshTokenResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SsoExchange operation middleware
func (sh *strictHandler) SsoExchange(w http.ResponseWriter, r *http.Request) {
	var request SsoExchangeRequestObject

	var body SsoExchangeJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SsoExchange(ctx, request.(SsoExchangeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SsoExchange")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SsoExchangeResponseObject); ok {
		if err := validResponse.VisitSsoExchangeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListBanks operation middleware
func (sh *strictHandler) ListBanks(w http.ResponseWriter, r *http.Request) {
	var request ListBanksRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListBanks(ctx, request.(ListBanksRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListBanks")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListBanksResponseObject); ok {
		if err := validResponse.VisitListBanksResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetBank operation middleware
func (sh *strictHandler) GetBank(w http.ResponseWriter, r *http.Request, slug Slug) {
	var request GetBankRequestObject

	request.Slug = slug

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetBank(ctx, request.(GetBankRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetBank")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetBankResponseObject); ok {
		if err := validResponse.VisitGetBankResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListQuestions operation middleware
func (sh *strictHandler) ListQuestions(w http.ResponseWriter, r *http.Request, slug Slug, params ListQuestionsParams) {
	var request ListQuestionsRequestObject

	request.Slug = slug
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListQuestions(ctx, request.(ListQuestionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListQuestions")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListQuestionsResponseObject); ok {
		if err := validResponse.VisitListQuestionsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListBankTags operation middleware
func (sh *strictHandler) ListBankTags(w http.ResponseWriter, r *http.Request, slug Slug, params ListBankTagsParams) {
	var request ListBankTagsRequestObject

	request.Slug = slug
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListBankTags(ctx, request.(ListBankTagsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListBankTags")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListBankTagsResponseObject); ok {
		if err := validResponse.VisitListBankTagsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMyOverview operation middleware
func (sh *strictHandler) GetMyOverview(w http.ResponseWriter, r *http.Request) {
	var request GetMyOverviewRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMyOverview(ctx, request.(GetMyOverviewRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMyOverview")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMyOverviewResponseObject); ok {
		if err := validResponse.VisitGetMyOverviewResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMyProgress operation middleware
func (sh *strictHandler) GetMyProgress(w http.ResponseWriter, r *http.Request, params GetMyProgressParams) {
	var request GetMyProgressRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMyProgress(ctx, request.(GetMyProgressRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMyProgress")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMyProgressResponseObject); ok {
		if err := validResponse.VisitGetMyProgressResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMyRecent operation middleware
func (sh *strictHandler) GetMyRecent(w http.ResponseWriter, r *http.Request, params GetMyRecentParams) {
	var request GetMyRecentRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMyRecent(ctx, request.(GetMyRecentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMyRecent")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMyRecentResponseObject); ok {
		if err := validResponse.VisitGetMyRecentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMyResume operation middleware
func (sh *strictHandler) GetMyResume(w http.ResponseWriter, r *http.Request, params GetMyResumeParams) {
	var request GetMyResumeRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMyResume(ctx, request.(GetMyResumeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMyResume")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMyResumeResponseObject); ok {
		if err := validResponse.VisitGetMyResumeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMyTagStats operation middleware
func (sh *strictHandler) GetMyTagStats(w http.ResponseWriter, r *http.Request, params GetMyTagStatsParams) {
	var request GetMyTagStatsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMyTagStats(ctx, request.(GetMyTagStatsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMyTagStats")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMyTagStatsResponseObject); ok {
		if err := validResponse.VisitGetMyTagStatsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetQuestion operation middleware
func (sh *strictHandler) GetQuestion(w http.ResponseWriter, r *http.Request, id int64) {
	var request GetQuestionRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetQuestion(ctx, request.(GetQuestionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetQuestion")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetQuestionResponseObject); ok {
		if err := validResponse.VisitGetQuestionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
