/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 用户名密码登录 */
        post: operations["passwordLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sso": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 用 Akasha id_token 换取本 API 的 token
         * @description web 与 iOS 各自完成 OIDC 流程后，把拿到的 id_token 交给本端点。
         *
         *     **id_token 由本 API 自己验签**（Akasha JWKS + issuer + audience）——
         *     绝不接受客户端自称的 sub：那等于任何人都能登录任意账号。
         */
        post: operations["ssoExchange"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 用 refresh token 换新的 access token */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 登出（吊销该会话） */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attempts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 记录一次作答（对错由服务端按参考答案判定） */
        post: operations["recordAttempt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 我的学习进度总览 */
        get: operations["getMyProgress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/tag-stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 按标签的正确率（「我哪里不会」）
         * @description `attempt ⋈ question_tag ⋈ tag` 聚合。每题只取**最近一次**作答参与统计 ——
         *     否则反复重做同一道错题会把正确率越刷越低，与直觉相反。
         */
        get: operations["getMyTagStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 继续学习（上次刷到哪）
         * @description 从 attempt 推导，不额外维护断点表 —— 少一处要保持一致的状态。
         */
        get: operations["getMyResume"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/banks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 题库列表 */
        get: operations["listBanks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/banks/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 题库详情与统计 */
        get: operations["getBank"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/banks/{slug}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 题库的标签列表（用于筛选与正确率热图） */
        get: operations["listBankTags"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/banks/{slug}/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 题目列表（分页 + 标签筛选） */
        get: operations["listQuestions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/questions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 单题详情（题干 + 选项 + 各方答案主张 + 解析 + 标签） */
        get: operations["getQuestion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Progress: {
            bankSlug: string;
            /** @description 题库总题数 */
            questionCount: number;
            /** @description 做过的题数（去重） */
            seenCount: number;
            /** @description 最近一次作答为对的题数 */
            correctCount: number;
            /** @description 最近一次作答为错的题数 */
            wrongCount: number;
            /** @description 最近一次自评 ≤2 的题数 */
            unsureCount: number;
            /** @description 总作答次数（含重做） */
            attemptCount: number;
            /** Format: date-time */
            lastActiveAt?: string;
        };
        TagStat: {
            /** Format: int64 */
            tagId: number;
            /** @enum {string} */
            type: "domain" | "service" | "concept";
            value: string;
            i18n?: {
                [key: string]: string;
            };
            /** @description 该标签下做过的题数 */
            total: number;
            correct: number;
            /**
             * Format: float
             * @description 正确率 0-100
             */
            rate: number;
        };
        /** @description 没有任何作答记录时 questionId 为空，前端应引导「开始第一题」 */
        Resume: {
            bankSlug?: string;
            /** Format: int64 */
            questionId?: number;
            externalNo?: number;
            stem?: string;
            /** Format: date-time */
            answeredAt?: string;
        };
        AttemptInput: {
            /** Format: int64 */
            questionId: number;
            /** @description 排序后的字母集合，如 "AB" */
            chosen: string;
            /** @description FSRS 标准四键自评 1=Again 2=Hard 3=Good 4=Easy */
            rating: number;
            durationMs?: number;
        };
        AttemptResult: {
            /** @description 服务端按参考答案判定 */
            correct: boolean;
            reference?: components["schemas"]["Reference"];
        };
        /**
         * @description 判对错用的参考答案。优先级 ai_verdict > community_vote > bank_label ——
         *     AI 是唯一看过全部信息并给出理由的来源；题库标注是四个来源里
         *     最不该被无条件信任的那个（38% 与社区投票不一致）。
         *     仅用于给出反馈信号，界面仍并列展示全部主张。
         */
        Reference: {
            answer: string;
            /** @enum {string} */
            source: "bank_label" | "community_vote" | "ai_verdict" | "user_note";
        };
        Credentials: {
            username: string;
            /** Format: password */
            password: string;
            /** @description 设备标识，用于「我的登录设备」 */
            deviceInfo?: string;
        };
        SsoExchange: {
            /** @description Akasha 签发的 id_token（由本 API 验签） */
            idToken: string;
            /** @description 设备标识，用于「我的登录设备」 */
            deviceInfo?: string;
        };
        RefreshRequest: {
            refreshToken: string;
        };
        /**
         * @description access 是 JWT（不落库，TTL 1h）；refresh 是不透明随机串（落库，可吊销）。
         *     对齐 geass-v3：refresh 不做成 JWT —— 生命周期以月计的凭证必须能撤回。
         */
        TokenPair: {
            accessToken: string;
            refreshToken: string;
            /** @description access token 剩余秒数（非绝对时间，免受客户端时钟偏差影响） */
            expiresIn: number;
            /** Format: int64 */
            accountId: number;
            display: string;
        };
        Error: {
            message: string;
        };
        Bank: {
            /** Format: int64 */
            id: number;
            /** @example aws-saa-c03 */
            slug: string;
            name: string;
            description?: string;
            /** @example zh */
            locale: string;
            /** @enum {string} */
            kind: "cert" | "custom";
        };
        BankDetail: components["schemas"]["Bank"] & {
            stats: components["schemas"]["BankStats"];
        };
        /** @description 题库的内容侧统计（与用户无关） */
        BankStats: {
            /** @description 题目总数 */
            questionCount: number;
            /** @description 已完成 AI 富化的题数 */
            enrichedCount: number;
            /** @description 题库标注与社区投票不一致的题数 */
            contestedCount: number;
        };
        /** @description 通用 (type, value) 结构，不硬编码任何特定题库的分类体系 */
        Tag: {
            /** Format: int64 */
            id: number;
            /** @enum {string} */
            type: "domain" | "service" | "concept";
            /** @example S3 */
            value: string;
            i18n?: {
                [key: string]: string;
            };
            /** @description 挂在该标签下的题数 */
            questionCount?: number;
        };
        Choice: {
            /** @example A */
            label: string;
            body: string;
        };
        /**
         * @description 一条带来源的答案主张。同一道题可以有多条，**故意不做合并**。
         *     `bank_label` 与 `community_vote` 不一致的情况占 38%，
         *     并列展示分歧并给出 AI 的裁决理由，正是本项目的核心价值。
         */
        AnswerClaim: {
            /** @enum {string} */
            source: "bank_label" | "community_vote" | "ai_verdict" | "user_note";
            /**
             * @description 排序后的字母集合，如 "AB"
             * @example B
             */
            answer: string;
            /** @description 无则省略 */
            confidence?: number;
            /** @description 为什么；AI 裁决必有 */
            rationale?: string;
            /** @description 如社区投票分布 {"A":80,"C":20} */
            meta?: {
                [key: string]: unknown;
            };
        };
        Explanation: {
            /** @enum {string} */
            source: "ai" | "editor" | "user";
            /** @example zh */
            locale: string;
            body: string;
        };
        QuestionSummary: {
            /** Format: int64 */
            id: number;
            /** @description 原题号，用于溯源 */
            externalNo: number;
            stem: string;
            /** @enum {string} */
            kind: "single" | "multi";
            pickCount: number;
            /** @description 题库标注与社区投票是否不一致 */
            contested: boolean;
            /** @description 是否已完成 AI 富化 */
            enriched: boolean;
        };
        QuestionDetail: components["schemas"]["QuestionSummary"] & {
            bankSlug: string;
            reference?: components["schemas"]["Reference"];
            /** @description 题目本身有缺陷时的说明（题库脏点），正常不出现 */
            dataIssue?: string;
            choices: components["schemas"]["Choice"][];
            claims: components["schemas"]["AnswerClaim"][];
            explanations: components["schemas"]["Explanation"][];
            tags: components["schemas"]["Tag"][];
            /** @description P0 解析阶段的告警，不静默丢弃 */
            warnings?: string[];
        };
        QuestionPage: {
            items: components["schemas"]["QuestionSummary"][];
            total: number;
            limit: number;
            offset: number;
        };
    };
    responses: {
        /** @description 登录尝试过于频繁 */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 资源不存在 */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description 题库 slug，如 aws-saa-c03 */
        Slug: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    passwordLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description 认证通过 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description 用户名或密码错误 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["TooManyRequests"];
        };
    };
    ssoExchange: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SsoExchange"];
            };
        };
        responses: {
            /** @description 账号已确立 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description id_token 无效 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["TooManyRequests"];
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description 已换发 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description refresh token 无效、已过期或已吊销 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description 已吊销（幂等：token 不存在也返回 204） */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    recordAttempt: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttemptInput"];
            };
        };
        responses: {
            /** @description 已记录 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttemptResult"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getMyProgress: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Progress"];
                };
            };
        };
    };
    getMyTagStats: {
        parameters: {
            query: {
                type: "domain" | "service" | "concept";
                /** @description 至少做过几道才纳入（样本太小的标签正确率没有意义） */
                minAttempts?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagStat"][];
                };
            };
        };
    };
    getMyResume: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resume"];
                };
            };
        };
    };
    listBanks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Bank"][];
                };
            };
        };
    };
    getBank: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 题库 slug，如 aws-saa-c03 */
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BankDetail"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listBankTags: {
        parameters: {
            query?: {
                /** @description 只返回某一类标签 */
                type?: "domain" | "service" | "concept";
            };
            header?: never;
            path: {
                /** @description 题库 slug，如 aws-saa-c03 */
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"][];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listQuestions: {
        parameters: {
            query?: {
                /** @description 标签 id，可重复；多个标签取交集 */
                tag?: number[];
                /** @description 只返回存在答案分歧的题（题库标注 ≠ 社区投票） */
                contested?: boolean;
                /** @description 只返回已完成 AI 富化的题 */
                enriched?: boolean;
                /**
                 * @description 学习模式过滤（wrong/unsure/unseen 需要 X-Melete-Account 头）：
                 *     wrong = 最近一次作答是错的；unsure = 最近一次自评 rating ≤ 2；
                 *     unseen = 从未作答。账号取自会话 JWT，非请求参数
                 */
                mode?: "wrong" | "unsure" | "unseen";
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                /** @description 题库 slug，如 aws-saa-c03 */
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionPage"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionDetail"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
}
