/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 用户名密码登录 */
        post: operations["passwordLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sso": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 用 Akasha id_token 换取本 API 的 token
         * @description web 与 iOS 各自完成 OIDC 流程后，把拿到的 id_token 交给本端点。
         *
         *     **id_token 由本 API 自己验签**（Akasha JWKS + issuer + audience）——
         *     绝不接受客户端自称的 sub：那等于任何人都能登录任意账号。
         */
        post: operations["ssoExchange"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/oidc/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 发起 Akasha 登录（浏览器导航，302）
         * @description 后端替所有客户端当 Akasha 的 OIDC client（confidential + PKCE），
         *     web 与 iOS 共用同一 client_id → 同一 pairwise sub → 同一账号。
         *     生成 state / nonce / PKCE 存签名 cookie 后 302 到 Akasha /authorize。
         *     本端点由 httpapi/oidc.go 手写挂载，不经生成层。
         */
        get: operations["oidcStart"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/oidc/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Akasha 回调（浏览器导航，302）
         * @description 验 state → 用 client_secret 换 code → 验 id_token 与 nonce → 确立账号 → 签发本站 token。
         *     · iOS：302 `melete://auth/callback#access_token=…&refresh_token=…&expires_in=…`
         *     · web：302 `{WEB_ORIGIN}/auth/callback?ticket=<refresh_token>&next=…`，
         *       web 服务端拿 ticket 去 /auth/refresh 换新的一对（轮换让 URL 里的票用一次即废）
         *     · 失败：302 回客户端并带 `oidc_error ∈ {cancelled, state, upstream, application}`
         */
        get: operations["oidcCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 用 refresh token 换新的 access token */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 登出（吊销该会话） */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attempts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 记录一次作答（对错由服务端按参考答案判定） */
        post: operations["recordAttempt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 我的学习进度总览 */
        get: operations["getMyProgress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/tag-stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 按标签的正确率（「我哪里不会」）
         * @description `attempt ⋈ question_tag ⋈ tag` 聚合。每题只取**最近一次**作答参与统计 ——
         *     否则反复重做同一道错题会把正确率越刷越低，与直觉相反。
         */
        get: operations["getMyTagStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 跨题库总览（今天 / 连续天数 / 累计）
         * @description 首页统计带。全部从 attempt 推导；连续天数按 Asia/Tokyo 自然日计。
         */
        get: operations["getMyOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 最近的学习会话（跨题库）
         * @description 从 attempt 推导：同一题库、同一 context、相邻间隔 ≤ 30 分钟的连续作答算一次会话。
         *     不存会话表 —— 会话是对事实的解释，不是事实。
         */
        get: operations["getMyRecent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 继续学习（上次刷到哪）
         * @description 从 attempt 推导，不额外维护断点表 —— 少一处要保持一致的状态。
         */
        get: operations["getMyResume"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/banks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 题库列表 */
        get: operations["listBanks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/banks/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 题库详情与统计 */
        get: operations["getBank"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/banks/{slug}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 题库的标签列表（用于筛选与正确率热图） */
        get: operations["listBankTags"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/banks/{slug}/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 题目列表（分页 + 标签筛选） */
        get: operations["listQuestions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/questions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 单题详情（题干 + 选项 + 各方答案主张 + 解析 + 标签） */
        get: operations["getQuestion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Progress: {
            bankSlug: string;
            /** @description 题库总题数 */
            questionCount: number;
            /** @description 做过的题数（去重） */
            seenCount: number;
            /** @description 最近一次作答为对的题数 */
            correctCount: number;
            /** @description 最近一次作答为错的题数 */
            wrongCount: number;
            /** @description 最近一次自评 ≤2 的题数 */
            unsureCount: number;
            /** @description 总作答次数（含重做） */
            attemptCount: number;
            /**
             * @description FSRS 复习队列里已到期的题数。
             *     ⚠️ **不含从没做过的题** —— 那些题没有卡片，属于「没做过」入口。
             *     两者混进一个数字，「今天要复习 300 题」就失去意义了，
             *     而那正是间隔重复最劝退的失败模式。
             */
            dueCount: number;
            /** Format: date-time */
            lastActiveAt?: string;
        };
        TagStat: {
            /** Format: int64 */
            tagId: number;
            /** @enum {string} */
            type: "domain" | "topic" | "concept";
            value: string;
            i18n?: {
                [key: string]: string;
            };
            /** @description 该标签下做过的题数 */
            total: number;
            correct: number;
            /**
             * Format: float
             * @description 正确率 0-100
             */
            rate: number;
        };
        /**
         * @description 「继续学习」的两条轨道，全部从 attempt 推导：
         *     · sequential —— 顺序进度：题号最小的没做过的题，无需存状态
         *     · focus —— 上次专项：最近一条 context.mode ∉ {unseen, all} 的作答的出处；从未做过专项时缺省
         */
        Resume: {
            bankSlug: string;
            sequential: components["schemas"]["SequentialCursor"];
            focus?: components["schemas"]["FocusCursor"];
        };
        Overview: {
            /** @description 今天的作答次数 */
            todayCount: number;
            /** @description 连续有作答的自然日数（含今天；今天没做则从昨天起算） */
            streakDays: number;
            /** @description 跨题库做过的题数（去重） */
            seenTotal: number;
        };
        StudySession: {
            bankSlug: string;
            bankName: string;
            context: components["schemas"]["DrillContext"];
            /** @description mode=tag 时为标签名，否则为 mode */
            label: string;
            tag?: components["schemas"]["Tag"];
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            endedAt: string;
            count: number;
            correct: number;
            /** @description 顺序刷时的起止题号，便于显示 "#400–#413" */
            firstNo?: number;
            lastNo?: number;
        };
        /** @description questionId 缺省 = 题库已全部做过一遍 */
        SequentialCursor: {
            /** Format: int64 */
            questionId?: number;
            externalNo?: number;
            stem?: string;
            /** @description 做过的题数（去重） */
            doneCount: number;
            /** @description 题库总题数 */
            totalCount: number;
            /**
             * Format: date-time
             * @description 上次顺序作答时间
             */
            lastAt?: string;
        };
        FocusCursor: {
            context: components["schemas"]["DrillContext"];
            /** @description mode=tag 时为标签 value，否则为 mode 名 */
            label: string;
            tag?: components["schemas"]["Tag"];
            /** @description 集合内做过的题数；只有 tag / contested 有意义 */
            done?: number;
            /** @description 集合当前大小 */
            total: number;
            /** Format: date-time */
            lastAt: string;
        };
        /** @description 一次作答的出处 —— 用户是从哪个入口做的这道题 */
        DrillContext: {
            /** @enum {string} */
            mode: "all" | "unseen" | "wrong" | "unsure" | "contested" | "tag" | "due";
            /**
             * Format: int64
             * @description mode=tag 时必填
             */
            tagId?: number;
        };
        AttemptInput: {
            /** Format: int64 */
            questionId: number;
            /** @description 排序后的字母集合，如 "AB" */
            chosen: string;
            /** @description FSRS 标准四键自评 1=Again 2=Hard 3=Good 4=Easy */
            rating: number;
            durationMs?: number;
            context?: components["schemas"]["DrillContext"];
        };
        AttemptResult: {
            /** @description 服务端按参考答案判定 */
            correct: boolean;
            reference?: components["schemas"]["Reference"];
            schedule?: components["schemas"]["ScheduleResult"];
        };
        /**
         * @description 这次作答之后的记忆调度结果（FSRS）。
         *
         *     **自评的可信度纠正**：`rating` 是用户按下的键、原样落进 attempt 表；
         *     `effectiveRating` 是实际喂给调度器的值。两者不同时 `reasons` 说明为什么 ——
         *     ⛔ 界面必须把理由显示出来，不得偷偷改调度。
         *     这与三方答案主张并列展示是同一条哲学：不替学习者下结论，把分歧摆出来。
         *
         *     当前的纠正规则：
         *     · 答错却自评「掌握 / 轻松」→ 压到 1（作答顺序是【揭晓之后】才自评，
         *       答案就在眼前，不存在「只是没算准」的解释空间）
         *     · 答对但用时短到读不完题面 → 压到 2（答对了，但这次答对提供不了「你会」的证据）
         *     · 没有任何答案主张的题（题库里 6 道）→ 不纠正，判不了对错就不拿对错说事
         */
        ScheduleResult: {
            /** @description 用户按下的自评键 */
            rating: number;
            /** @description 实际用于调度的评分，只会 ≤ rating */
            effectiveRating: number;
            /** @description 纠正理由，未纠正时为空数组 */
            reasons: string[];
            /**
             * Format: date-time
             * @description 这道题下次该出现的时间（UTC）
             */
            due: string;
            /**
             * @description 调度后的卡片状态
             * @enum {string}
             */
            state: "new" | "learning" | "review" | "relearning";
        };
        /**
         * @description 判对错用的参考答案。优先级 ai_verdict > community_vote > bank_label ——
         *     AI 是唯一看过全部信息并给出理由的来源；题库标注是四个来源里
         *     最不该被无条件信任的那个（38% 与社区投票不一致）。
         *     仅用于给出反馈信号，界面仍并列展示全部主张。
         */
        Reference: {
            answer: string;
            /** @enum {string} */
            source: "bank_label" | "community_vote" | "ai_verdict" | "user_note";
        };
        Credentials: {
            username: string;
            /** Format: password */
            password: string;
            /** @description 设备标识，用于「我的登录设备」 */
            deviceInfo?: string;
        };
        SsoExchange: {
            /** @description Akasha 签发的 id_token（由本 API 验签） */
            idToken: string;
            /** @description 设备标识，用于「我的登录设备」 */
            deviceInfo?: string;
        };
        RefreshRequest: {
            refreshToken: string;
        };
        /**
         * @description access 是 JWT（不落库，TTL 1h）；refresh 是不透明随机串（落库，可吊销）。
         *     对齐 geass-v3：refresh 不做成 JWT —— 生命周期以月计的凭证必须能撤回。
         */
        TokenPair: {
            accessToken: string;
            refreshToken: string;
            /** @description access token 剩余秒数（非绝对时间，免受客户端时钟偏差影响） */
            expiresIn: number;
            /** @description 账号 id（canonical UUIDv7 文本） */
            accountId: string;
            display: string;
        };
        Error: {
            message: string;
        };
        Bank: {
            /** Format: int64 */
            id: number;
            /** @example aws-saa-c03 */
            slug: string;
            name: string;
            description?: string;
            /** @example zh */
            locale: string;
            /** @enum {string} */
            kind: "cert" | "custom";
            meta: components["schemas"]["BankMeta"];
        };
        /**
         * @description 题库的**自描述展示元数据**。前端不得写死任何题库特有的词：
         *     标签轴叫什么（AWS 是「服务」、LPIC 是「命令与工具」）、考纲权重、及格线，
         *     全部从这里读。换一个题库只有这个对象不同，页面代码零改动。
         */
        BankMeta: {
            /** @description 以标签 type（domain / topic / concept）为键 */
            tagTypes?: {
                [key: string]: components["schemas"]["TagTypeMeta"];
            };
            /** @description 官方及格分（无则不显示及格线） */
            passScore?: number;
            /** @description 满分 */
            maxScore?: number;
        };
        TagTypeMeta: {
            /** @description locale → 该标签轴的显示名 */
            label?: {
                [key: string]: string;
            };
            /** @description 标签 value → 官方权重百分比（通常只有 domain 轴有） */
            weights?: {
                [key: string]: number;
            };
        };
        BankDetail: components["schemas"]["Bank"] & {
            stats: components["schemas"]["BankStats"];
        };
        /** @description 题库的内容侧统计（与用户无关） */
        BankStats: {
            /** @description 题目总数 */
            questionCount: number;
            /** @description 已完成 AI 富化的题数 */
            enrichedCount: number;
            /** @description 题库标注与社区投票不一致的题数 */
            contestedCount: number;
        };
        /** @description 通用 (type, value) 结构，不硬编码任何特定题库的分类体系 */
        Tag: {
            /** Format: int64 */
            id: number;
            /** @enum {string} */
            type: "domain" | "topic" | "concept";
            /** @example S3 */
            value: string;
            i18n?: {
                [key: string]: string;
            };
            /** @description 挂在该标签下的题数 */
            questionCount?: number;
        };
        Choice: {
            /** @example A */
            label: string;
            body: string;
        };
        /**
         * @description 一条带来源的答案主张。同一道题可以有多条，**故意不做合并**。
         *     `bank_label` 与 `community_vote` 不一致的情况占 38%，
         *     并列展示分歧并给出 AI 的裁决理由，正是本项目的核心价值。
         */
        AnswerClaim: {
            /** @enum {string} */
            source: "bank_label" | "community_vote" | "ai_verdict" | "user_note";
            /**
             * @description 排序后的字母集合，如 "AB"
             * @example B
             */
            answer: string;
            /** @description 无则省略 */
            confidence?: number;
            /** @description 为什么；AI 裁决必有 */
            rationale?: string;
            /** @description 如社区投票分布 {"A":80,"C":20} */
            meta?: {
                [key: string]: unknown;
            };
        };
        Explanation: {
            /** @enum {string} */
            source: "ai" | "editor" | "user";
            /** @example zh */
            locale: string;
            body: string;
        };
        QuestionSummary: {
            /** Format: int64 */
            id: number;
            /** @description 原题号，用于溯源 */
            externalNo: number;
            stem: string;
            /** @enum {string} */
            kind: "single" | "multi";
            pickCount: number;
            /** @description 题库标注与社区投票是否不一致 */
            contested: boolean;
            /** @description 是否已完成 AI 富化 */
            enriched: boolean;
        };
        QuestionDetail: components["schemas"]["QuestionSummary"] & {
            bankSlug: string;
            reference?: components["schemas"]["Reference"];
            /** @description 题目本身有缺陷时的说明（题库脏点），正常不出现 */
            dataIssue?: string;
            choices: components["schemas"]["Choice"][];
            claims: components["schemas"]["AnswerClaim"][];
            explanations: components["schemas"]["Explanation"][];
            tags: components["schemas"]["Tag"][];
            /** @description P0 解析阶段的告警，不静默丢弃 */
            warnings?: string[];
        };
        QuestionPage: {
            items: components["schemas"]["QuestionSummary"][];
            total: number;
            limit: number;
            offset: number;
        };
    };
    responses: {
        /** @description 登录尝试过于频繁 */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 资源不存在 */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description 题库 slug；缺省 = 当前题库（现阶段为第一个题库） */
        BankQuery: string;
        /** @description 题库 slug，如 aws-saa-c03 */
        Slug: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    passwordLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description 认证通过 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description 用户名或密码错误 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["TooManyRequests"];
        };
    };
    ssoExchange: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SsoExchange"];
            };
        };
        responses: {
            /** @description 账号已确立 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description id_token 无效 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["TooManyRequests"];
        };
    };
    oidcStart: {
        parameters: {
            query?: {
                /**
                 * @description 登录后去向。web 传本站绝对路径（如 /banks/aws-saa-c03）；
                 *     iOS 固定传 `melete://auth/callback`（可带 ?then=应用内目标）。其余值一律丢弃。
                 */
                next?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 跳转到 Akasha */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    oidcCallback: {
        parameters: {
            query?: {
                code?: string;
                state?: string;
                error?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 跳转回客户端 */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description 已换发 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description refresh token 无效、已过期或已吊销 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description 已吊销（幂等：token 不存在也返回 204） */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    recordAttempt: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttemptInput"];
            };
        };
        responses: {
            /** @description 已记录 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttemptResult"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getMyProgress: {
        parameters: {
            query?: {
                /** @description 题库 slug；缺省 = 当前题库（现阶段为第一个题库） */
                bank?: components["parameters"]["BankQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Progress"];
                };
            };
        };
    };
    getMyTagStats: {
        parameters: {
            query: {
                /** @description 题库 slug；缺省 = 当前题库（现阶段为第一个题库） */
                bank?: components["parameters"]["BankQuery"];
                type: "domain" | "topic" | "concept";
                /** @description 至少做过几道才纳入（样本太小的标签正确率没有意义） */
                minAttempts?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagStat"][];
                };
            };
        };
    };
    getMyOverview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Overview"];
                };
            };
        };
    };
    getMyRecent: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudySession"][];
                };
            };
        };
    };
    getMyResume: {
        parameters: {
            query?: {
                /** @description 题库 slug；缺省 = 当前题库（现阶段为第一个题库） */
                bank?: components["parameters"]["BankQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resume"];
                };
            };
        };
    };
    listBanks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Bank"][];
                };
            };
        };
    };
    getBank: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 题库 slug，如 aws-saa-c03 */
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BankDetail"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listBankTags: {
        parameters: {
            query?: {
                /** @description 只返回某一类标签 */
                type?: "domain" | "topic" | "concept";
            };
            header?: never;
            path: {
                /** @description 题库 slug，如 aws-saa-c03 */
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"][];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listQuestions: {
        parameters: {
            query?: {
                /** @description 标签 id，可重复；多个标签取交集 */
                tag?: number[];
                /** @description 只返回存在答案分歧的题（题库标注 ≠ 社区投票） */
                contested?: boolean;
                /** @description 只返回已完成 AI 富化的题 */
                enriched?: boolean;
                /**
                 * @description 学习模式过滤（全部需要会话，账号取自 JWT 而非请求参数）：
                 *     wrong = 最近一次作答是错的；unsure = 最近一次自评 rating ≤ 2；
                 *     unseen = 从未作答；
                 *     due = FSRS 复习队列，卡片已到期。
                 *
                 *     ⚠️ due 与 unseen 互斥且不重叠：没做过的题没有卡片，不算「到期」。
                 *     两者混进一个数字会让「今天要复习 300 题」失去意义。
                 *     ⚠️ due 按【到期时间】升序返回，其余模式按原题号 —— 复习队列不是浏览列表。
                 */
                mode?: "wrong" | "unsure" | "unseen" | "due";
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                /** @description 题库 slug，如 aws-saa-c03 */
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionPage"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionDetail"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
}
